// <auto-generated />
using Employee.Backend.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Employee.Backend.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20210713200024_seedData")]
    partial class seedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Employee.Backend.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Blog")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hobbies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hometown")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Job")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Empolyees");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Blog = "www.google.com",
                            Hobbies = "Surfing",
                            Hometown = "Playa de las Americas, Tenerife",
                            Job = "Police Officer",
                            Motto = "Hey, have you tried Surf?",
                            Name = "Colin Farrell"
                        },
                        new
                        {
                            Id = 2L,
                            Blog = "www.github.com",
                            Hobbies = "Partying",
                            Hometown = "Santa Cruz, Tenerife",
                            Job = "Average Guy",
                            Motto = "Party never sleeps.",
                            Name = "Al Pacino"
                        },
                        new
                        {
                            Id = 3L,
                            Blog = "www.stackoverflow.com",
                            Hobbies = "Diving",
                            Hometown = "El Medano, Tenerife",
                            Job = "The Postman",
                            Motto = "Bigger. Better. Postman.",
                            Name = "Kevin Costner"
                        },
                        new
                        {
                            Id = 4L,
                            Blog = "www.npm.com",
                            Hobbies = "Basketball",
                            Hometown = "Puerto de la Cruz, Tenerife",
                            Job = "Receptionist at Hotel",
                            Motto = "Basketball, the freshmaker.",
                            Name = "Jack Nicholson"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
